### ISSUE TITLE
chore: Audit prep checklist

### ISSUE THREAD

**Issue by parseb** [Developer-DAO/code-claim-site#93]
### Audit prep checklist ([reference](https://diligence.consensys.net/posts/2019/09/how-to-prepare-for-a-smart-contract-audit/))

- [ ] Documentation
  - [ ] Add corresponding NatSpec for all externally callable functions  
  - [ ] For the overall system
  - [ ] For each unique contract within the system
- [ ] Clean code
  - [ ] Run a linter (like [EthLint](https://www.ethlint.com/))
  - [ ] Fix compiler warnings
  - [ ] Remove TODO and FIXME comments
  - [ ] Delete unused code
- [ ] Testing
  - [x] README gives clear instructions for running tests
  - [x] Testing dependencies are packaged with the code OR are listed including versions
- [ ] Automated Analysis
- [ ] Frozen code
  - [ ] Halt development of the contract code
  - [ ] Provide commit hash for the audit to target

**Comment by embiem** [comment]
I just created the branchaudit and tag audit-01. The current commit hash is 67150ee4a05aa9c96c4765e70143185476ae37bc
